best_idea/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp.views import index

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

myapp/urls.py
from django.urls import path
from myapp import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('works/', views.works, name='works'),
    path('contact/', views.contact, name='contact'),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Work(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='works/photos', default='default_image.jpg')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('myapp:contact')

    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.subject
    

myapp/views.py
from django.shortcuts import render
from .models import Work
from .mailchimp_utils import subscribe_user_to_mailchimp

def index(request):
    return render(request, 'myapp/index.html')

def about(request):
    return render(request, 'myapp/about.html')

def services(request):
    return render(request, 'myapp/services.html')

def portfolio(request):
    return render(request, 'myapp/portfolio.html')

def works(request):
    works = Work.objects.all()
    return render(request, 'myapp/works.html', {'works': works})



def contact(request):
    return render(request, 'myapp/contact.html')

myapp/templates/myapp/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>BEST IDEA GRAPHIX</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/favicon.png' %}" rel="apple-touch-icon">
  
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
<link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
<link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

<!-- Template Main CSS File -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope d-flex align-items-center"><a href="sottiegadson@gmail.com">sottiegadson@gmail.com</a></i>
        <i class="bi bi-phone d-flex align-items-center ms-4"><span>+233 596 032 773</span></i>
      </div>
      <div class="social-links d-none d-md-flex align-items-center">
        <a href="https://twitter.com/boaz_sottie?t=CLkxSuXrgz-C7Pfs-rgzaw&s=09" class="twitter"><i class="bi bi-twitter"></i></a>
         <a href="https://www.facebook.com/sottie.carl?mibextid=ZbWKwL" class="facebook"><i class="bi bi-facebook"></i></a>
         <a href="https://instagram.com/sottie_boaz" class="instagram"><i class="bi bi-instagram"></i></a>
         <a href="https://www.linkedin.com/in/boaz-sottie-5aa2631a4" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="index.html">BEST IDEA GRAPHIX<span>.</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt=""></a>-->

      <nav id="navbar" class="navbar">
        <ul>
            <li><a class="nav-link scrollto " href="{% url 'myapp:index' %}">Home</a></li>
            <li><a class="nav-link scrollto active" href="{% url 'myapp:about' %}">About</a></li>
            <li><a class="nav-link scrollto" href="{% url 'myapp:services' %}">Services</a></li>
            <li><a class="nav-link scrollto  " href="{% url 'myapp:portfolio' %}">Portfolio</a></li>
            <li><a class="nav-link scrollto" href="{% url 'myapp:works' %}">Works</a></li>
            <li><a class="nav-link scrollto" href="{% url 'myapp:contact' %}">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

<!-- ======= About Section ======= -->
<section id="about" class="about section-bg">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>About</h2>
      <h3>Find Out More <span>About Us</span></h3>
      <p>Get to Know us..</p>
    </div>

    <div class="row">
      <div class="col-lg-6" data-aos="fade-right" data-aos-delay="100">
        <img src="{% static 'img/about.jpg' %}" class="img-fluid" alt="">
      </div>
      <div class="col-lg-6 pt-4 pt-lg-0 content d-flex flex-column justify-content-center" data-aos="fade-up" data-aos-delay="100">
        <h3>Welcome to Best Idea Graphix</h3>
        <p class="fst-italic">
          At Best Idea Graphix, we are passionate about the power of visual communication and the impact it can have on your brand. Our page is dedicated to providing you with valuable insights, inspiration, and resources related to graphic design.
        </p>
        <p>
          We believe that great design has the ability to captivate, inspire, and convey your message effectively. Whether you're a seasoned designer looking for fresh ideas or a business owner seeking to enhance your brand's visual identity, our page is your go-to destination for all things graphic design.
        </p>
      </div>
    </div>

  </div>
</section><!-- End About Section -->
<!-- ======= Footer ======= -->
<footer id="footer">

  <div class="footer-newsletter">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6">
          <h4>Join Our Newsletter</h4>
          <p>Subscribe to our daily Newsletter</p>
          <form  action="https://formspree.io/f/xlekkjqq" method="POST">
            <input type="email" name="email"><input type="submit" value="Subscribe">
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="footer-top">
    <div class="container">
      <div class="row">

        <div class="col-lg-3 col-md-6 footer-contact">
          <h3>BEST IDEA GRAPHIX<span>.</span></h3>
          <p>
            Airport Hills <br>
            Greater Accra<br>
            Ghana <br><br>
            <strong>Phone:</strong> +233 596 032 773<br>
            <strong>Email:</strong> sottiegadson@gmail.com<br>
          </p>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'myapp:index' %}">Home</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'myapp:about' %}">About us</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'myapp:services' %}">Services</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'myapp:portfolio' %}">Web Design</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'myapp:portfolio' %}">Logo Design</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">UI/UX Design</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing Collateral</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'myapp:portfolio' %}">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Our Social Networks</h4>
          <p>Connect with us on our social media</p>
          <div class="social-links mt-3">
            <a href="https://twitter.com/boaz_sottie?t=CLkxSuXrgz-C7Pfs-rgzaw&s=09" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="https://www.facebook.com/sottie.carl?mibextid=ZbWKwL" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="https://instagram.com/sottie_boaz" class="instagram"><i class="bx bxl-instagram"></i></a>
            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
            <a href="https://www.linkedin.com/in/boaz-sottie-5aa2631a4" class="linkedin"><i class="bx bxl-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="container py-4">
    <div class="copyright">
      &copy; Copyright <strong><span>Best Idea Graphix</span></strong>. All Rights Reserved. Design By  <strong><span>Boaz sottie</span></strong>
    </div>
  </div>
</footer><!-- End Footer -->

<div id="preloader"></div>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'vendor/aos/aos.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>


</body>

</html>

myapp/templates/myapp/contact.html
{% load static %}
 <!DOCTYPE html>
 <html lang="en">
 
 <head>
   <meta charset="utf-8">
   <meta content="width=device-width, initial-scale=1.0" name="viewport">
 
   <title>BEST IDEA GRAPHIX</title>
   <meta content="" name="description">
   <meta content="" name="keywords">
 
   <!-- Favicons -->
   <link href="{% static 'img/favicon.png' %}" rel="icon">
   <link href="{% static 'img/favicon.png' %}" rel="apple-touch-icon">
   
   <!-- Google Fonts -->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
 
   <!-- Vendor CSS Files -->
 <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
 <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
 <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
 <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
 <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
 <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
 
 <!-- Template Main CSS File -->
 <link href="{% static 'css/style.css' %}" rel="stylesheet">
 
 
 </head>
 
 <body>
 
   <!-- ======= Top Bar ======= -->
   <section id="topbar" class="d-flex align-items-center">
     <div class="container d-flex justify-content-center justify-content-md-between">
       <div class="contact-info d-flex align-items-center">
         <i class="bi bi-envelope d-flex align-items-center"><a href="sottiegadson@gmail.com">sottiegadson@gmail.com</a></i>
         <i class="bi bi-phone d-flex align-items-center ms-4"><span>+233 596 032 773</span></i>
       </div>
       <div class="social-links d-none d-md-flex align-items-center">
         <a href="https://twitter.com/boaz_sottie?t=CLkxSuXrgz-C7Pfs-rgzaw&s=09" class="twitter"><i class="bi bi-twitter"></i></a>
         <a href="https://www.facebook.com/sottie.carl?mibextid=ZbWKwL" class="facebook"><i class="bi bi-facebook"></i></a>
         <a href="https://instagram.com/sottie_boaz" class="instagram"><i class="bi bi-instagram"></i></a>
         <a href="https://www.linkedin.com/in/boaz-sottie-5aa2631a4" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
       </div>
     </div>
   </section>
 
   <!-- ======= Header ======= -->
   <header id="header" class="d-flex align-items-center">
     <div class="container d-flex align-items-center justify-content-between">
 
       <h1 class="logo"><a href="index.html">BEST IDEA GRAPHIX<span>.</span></a></h1>
       <!-- Uncomment below if you prefer to use an image logo -->
       <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt=""></a>-->
 
       <nav id="navbar" class="navbar">
         <ul>
          <li><a class="nav-link scrollto " href="{% url 'myapp:index' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'myapp:about' %}">About</a></li>
          <li><a class="nav-link scrollto" href="{% url 'myapp:services' %}">Services</a></li>
          <li><a class="nav-link scrollto " href="{% url 'myapp:portfolio' %}">Portfolio</a></li>
          <li><a class="nav-link scrollto" href="{% url 'myapp:works' %}">Works</a></li>
          <li><a class="nav-link scrollto active" href="{% url 'myapp:contact' %}">Contact</a></li>
         </ul>
         <i class="bi bi-list mobile-nav-toggle"></i>
       </nav><!-- .navbar -->
 
     </div>
   </header><!-- End Header -->
 <!-- ======= Contact Section ======= -->
 <section id="contact" class="contact">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>Contact</h2>
      <h3><span>Contact Us</span></h3>
      <p>Contact us by filling the form below</p>
    </div>

    <div class="row" data-aos="fade-up" data-aos-delay="100">
      <div class="col-lg-6">
        <div class="info-box mb-4">
          <i class="bx bx-map"></i>
          <h3>Our Address</h3>
          <p>Vista De Esi, Airport Hills</p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="info-box  mb-4">
          <i class="bx bx-envelope"></i>
          <h3>Email Us</h3>
          <p>sottiegadson@gmail.com</p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="info-box  mb-4">
          <i class="bx bx-phone-call"></i>
          <h3>Call Us</h3>
          <p>+233 596 032 773</p>
        </div>
      </div>

    </div>

    <div class="row" data-aos="fade-up" data-aos-delay="100">

      <div class="col-lg-6 ">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d15882.718506535526!2d-0.14013925!3d5.61424!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sgh!4v1684842550244!5m2!1sen!2sgh" width="450" height="397" style="border: 5px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>

      <div class="col-lg-6">
        <form action="https://formspree.io/f/xlekkjqq" method="POST">
          <div class="row">
            <div class="col form-group">
              <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
            </div>
            <div class="col form-group">
              <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
            </div>
          </div>
          <br>
          <div class="form-group">
            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
          </div>
          <br>
          <div class="form-group">
            <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
          </div>
          <br>
          <div class="text-center">
            <button type="submit" class="btn btn-primary">Send Message</button>
          </div>
        </form>
      </div>

    </div>

  </div>
</section><!-- End Contact Section -->
 
 <!-- ======= Footer ======= -->
 <footer id="footer">

  <div class="footer-newsletter">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6">
          <h4>Join Our Newsletter</h4>
          <p>Subscribe to our daily Newsletter</p>
          <form  action="https://formspree.io/f/xlekkjqq" method="POST">
            <input type="email" name="email"><input type="submit" value="Subscribe">
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="footer-top">
    <div class="container">
      <div class="row">

        <div class="col-lg-3 col-md-6 footer-contact">
          <h3>BEST IDEA GRAPHIX<span>.</span></h3>
          <p>
            Airport Hills <br>
            Greater Accra<br>
            Ghana <br><br>
            <strong>Phone:</strong> +233 596 032 773<br>
            <strong>Email:</strong> sottiegadson@gmail.com<br>
          </p>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="index.html">Home</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="about.html">About us</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="services.html">Services</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Logo Design</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">UI/UX Design</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing Collateral</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Our Social Networks</h4>
          <p>Connect with us on our social media</p>
          <div class="social-links mt-3">
            <a href="https://twitter.com/boaz_sottie?t=CLkxSuXrgz-C7Pfs-rgzaw&s=09" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="https://www.facebook.com/sottie.carl?mibextid=ZbWKwL" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="https://instagram.com/sottie_boaz" class="instagram"><i class="bx bxl-instagram"></i></a>
            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
            <a href="https://www.linkedin.com/in/boaz-sottie-5aa2631a4" class="linkedin"><i class="bx bxl-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="container py-4">
    <div class="copyright">
      &copy; Copyright <strong><span>Best Idea Graphix</span></strong>. All Rights Reserved. Design By  <strong><span>Boaz sottie</span></strong>
    </div>
  </div>
</footer><!-- End Footer -->

<div id="preloader"></div>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'vendor/aos/aos.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>


</body>

</html>